return PlaceObj('ModDef', {
	'title', "Squad Bag Done Right",
	'description', '[h1]Squad Bag Done Right[/h1]\n\nThis mod streamlines inventory management by automatically moving eligible items from merc inventories to their respective squad bags and providing advanced redistribution tools for your squads.\n\nThis is an updated version of the original Crafting items to Squad bag mod and fixes the bugs and shortcomings of that mod.\n \n\n[b]Key Features:[/b]\n• [b]Immediate effect:[/b] Unlike the old mod, changing the item categories in the mod options has immediate effect. No reloading of a save or restarting of the game necessary like in the old mod.\n• [b]Scrapping and cashing in:[/b] Cashing in or scrapping item stacks in the squad bag now works for the new items. This has been fixed\n• [b]Non-stackable items:[/b] Non-stackable items like the big valuables (Figurine, Golden Dog, etc.) will no longer vanish when moving them to the squad bag, like in the old mod. This has been fixed.\n• [b]Automatic Item Movement:[/b] Automatically moves crafting materials, skill books, and valuables to the squad bag upon game start/load or when mod options are changed. (Can be toggled in options).\n• [b]Context Menu Allocation:[/b] Right-click on Ammo or Craftables in any squad bag to redistribute them across all player squads in the current sector using proportional allocation of ammo based on the total magazine size of weapons in each squad. Supports standard ammo, 40mm, mortar shells, flares, and HE rockets (Ordnance).\n• [b]Skill-Based Crafting Allocation:[/b] Redistributes explosives and detonators based on the highest Explosive skill in each squad, and other craftables (like steel pipes) based on the highest Mechanical skill.\n• [b]Minimum Skill Threshold:[/b] Allocation only considers mercs with a relevant skill of 60 or higher to ensure items go to the most capable hands.\n• [b]Improved Sorting:[/b] The new items are now sorted properly. Gun powder ends up next to parts and meds, then comes ammo, heavy ammo, craftables (first explosives, then mechanics stuff) and finally valuables\n• [b]Data Integrity & Safety:[/b] Includes robust "Evict Invalid Items" logic and extensive safety checks to prevent item loss or crashes. When you deactivate a category of items for the squad bag they are automatically moved back to the merc inventories or (if those are full) to the sector stash.\n\n \n[b]Technical Information:[/b]\nMake sure you deactivate the item categories in the mod options and make a new save before you uninstall the mod, otherwise your items will be not accessible in the squad bag anymore. Deactivating the categories in the mod options moves them safely back to the inventories or sector stash. Save after that has happened. Then you can uninstall the mod safely.',
	'image', "Mod/QGujmyS/Images/thumbnail.jpg",
	'last_changes', "Updated description",
	'id', "QGujmyS",
	'author', "KeldorKatarn",
	'version_major', 1,
	'version', 20,
	'lua_revision', 233360,
	'saved_with_revision', 366685,
	'code', {
		"Code/Script.lua",
		"Code/Allocation.lua",
	},
	'loctables', {
		{
			filename = "Languages/en.csv",
			language = "English",
		},
	},
	'default_options', {
		sbdr_auto_move_to_bag = true,
		sbdr_crafting_items = true,
		sbdr_skill_mags = true,
		sbdr_valuables = true,
	},
	'saved', 1775537628,
	'code_hash', 5917284082875257936,
	'screenshot1', "Mod/QGujmyS/Images/screenshot1.jpg",
	'screenshot2', "Mod/QGujmyS/Images/screenshot2.jpg",
	'affected_resources', {},
	'steam_id', "3701666600",
	'TagOther', true,
	'TagUI', true,
	'TagWeapons&Items', true,
})